<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7NFQM15" failures="1" tests="1" name="Test4" time="3.048" errors="0" timestamp="2024-04-15T19:31:02 IST">
  <testcase classname="ui.ListenerOnTestFailure" name="launchappln" time="3.011">
    <failure type="java.lang.AssertionError" message="Testcase failed due to mismatch  expected [https://practice.expandtesting.com/secure] but found [https://practice.expandtesting.com/login]">
      <![CDATA[java.lang.AssertionError: Testcase failed due to mismatch  expected [https://practice.expandtesting.com/secure] but found [https://practice.expandtesting.com/login]
at ui.ListenerOnTestFailure.launchappln(ListenerOnTestFailure.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- launchappln -->
</testsuite> <!-- Test4 -->
